### ISSUE TITLE
`v6.0.0-beta.2` doesn't load

### ISSUE THREAD

**Issue by def1149** [dermotduffy/frigate-hass-card#1543]
**Checklist:**

- [ ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
6.0.0-beta1

**Last working release (if known):**
5.2.0
**Browser and Operating System:**
Chrome current , Windows 11 current

**Description of problem:**
Started getting these errors in the Frigate log 
![image](https://github.com/user-attachments/assets/9c2a1e72-5fa9-4dbc-bbdc-1180dbf48c1f)

No PTZ control is enabled on the cards

Also dashboards with Frigate cards wouldn't open and hang with Page Unresponsive. 
**Frigate card diagnostic information**

Can't card won't open

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Rolled back to version 5.2.0 and everything is OK again

**Comment by dermotduffy** [comment]
The log messages are harmless. The Frigate card asks Frigate whether or not each camera supports PTZ, and if it does not, Frigate logs that message. If you'd like those errors to stop, my recommendation is to file an issue (or even better make the fix yourself) upstream in Frigate -- I don't think it should generate an error in this case.

You can test it yourself, just visit this and you'll generate an error on a non-PTZ camera (this is what the card is doing):

```
http://YOUR_FRIGATE_INSTANCE/api/master_bedroom/ptz/info
```

Your issues with the card not loading are almost certainly something different, not related to that error message. I just released [`v6.0.0-beta.2`](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.2) which fixed at least one bug with initialization that may or may not be related. Give it a shot.

**Comment by def1149** [comment]
1. I confirmed the PTZ error is being thrown by the .../ptz/info call. Thanks
    I agree, the ptz info call should not error unless the call itself fails because it's ostensibly there to determine if ptz capability 
    exists.  
2. I DL beta 2 and the card not loading errors are still occurring and hanging the page

**Comment by dermotduffy** [comment]
OK, lets ignore topic #1 then. Feel free to pursue upstream with Frigate itself.

For topic #2, can you share your card configuration (hold down the Frigate button for a few seconds and you'll get diagnostics). Also (or if the card literally won't show up at all), please check your Javascript console (Press F12) and see if there are any errors there. A screenshot and/or description of what you see would also be welcome.

**Comment by def1149** [comment]
loaded beta 3 ... same problem.  Any page with Frigate card hangs 
The  Javascript console gave 69K of these same warnings in just few seconds sonethings hung in a loop

![image](https://github.com/user-attachments/assets/1036b912-73e7-4209-88d1-bfca781db4ca)

**Comment by def1149** [comment]
http on local net but I use nabu casa app on phones for remote

**Comment by dermotduffy** [comment]
Does it work when you access it over https?

**Comment by def1149** [comment]
Didn't try that ... 
I'll try

**Comment by dermotduffy** [comment]
OK. I know what the problem is!

**Comment by dermotduffy** [comment]
Fix will be in the next build. The issue boils down to your config presumably containing the `always_connected` parameter for your microphone, but accessing Home Assistant over `http` (which will never support a microphone). This causes the card to spin trying to initialize the microphone, which it will never succeed with. Presumably you are the first person to run into this combination!

**Comment by def1149** [comment]
Well, ultimately I wouldn't have been the only one. And now I know to look at the Javascript console if I have any future HA GUI issues, Thanks
