### ISSUE TITLE
Frigate lovelace card doesn't play clips

### ISSUE THREAD

**Issue by latum** [dermotduffy/frigate-hass-card#55]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
v1.0.0

**Last working release (if known):**
v0.9 I believe

**Browser and Operating System:**
Simplest way to replicate is via Chrome browser on Windows 10 but I can confirm that the same behavior occurs on Edge as well as iOS HA app.

**Description of problem:**
opening the clips gallery from the card. I can see the clips but selecting one results in a player window with the navigation circles (previous and next clip images) but a grey background and no movie playing. After 30 seconds or so the card reverts to the live view which is my default.
![image](https://user-images.githubusercontent.com/5102924/132144645-023a968e-3f61-48d1-8c37-3b9d447a6866.png)

**Javascript errors shown in the web inspector (if applicable):**
I don't see any Javascript errors.

**Additional information:**
Running latest frigate integration and frigate NVR add-on

**Comment by latum** [comment]
I can confirm that the frigate clips gallery works correctly from the media browser

**Comment by dermotduffy** [comment]
Thanks for the helping debug @latum !

Don't suppose it plays when you click the play icon? If yes, it might be https://github.com/blakeblackshear/frigate/issues/1637 .

If not, you said it _does_ play from the Home Assistant Media Browser, is this for the very same clip?

Do you see anything logged in the Javascript console? (Try a fresh card reload, and try to play a clip and see if anything interesting gets logged?)

**Comment by latum** [comment]
No problem @dermotduffy I'm just stoked that this is available for HA. Answers:

1. No it does not play when I click on the arrow. The black buffering circle rotates and the play icon changes to pause but the background remains grey. Hovering over the 3 dots does show the date/time as well as duration of the actual clip plus percentage confidence of detection
2. Yes, the exact same clip plays from the media Browser -> Frigate -> Clips and shows the same date/time, duration and confidence

**Comment by elderec** [comment]
I'm experiencing same symptoms. Console shows:

`Uncaught DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at WebSocket.ws.onmessage (https://home.contoso.com/webrtc/webrtc-camera.js?v2.0.2:88:34)
ws.onmessage @ webrtc-camera.js?v2.0.2:88`

**Comment by dermotduffy** [comment]
@elderec That console message is a red herring. As you can see in the text, it's from WebRTC not the Frigate card. I ran into that myself, it's a harmless error message the WebRTC is logging. It's actually already been fixed in the WebRTC code, they just haven't done a new release yet.

@elderec Sounds like the clips are not playing for you either. Even when you get the failed clip load, if you click play manually does it work or still fails as @latum described?

@latum or @elderec :
 - In Home Assistant, can you go `Configuration -> Integrations -> Frigate -> Click "<N> devices" -> Give me the model number it shows? I take it you are using Home Assistant OS, with the Frigate Addon?

**Comment by latum** [comment]
Here's the Device info: 1.1.2/0.8.4-5043040

**Comment by latum** [comment]
and yes, HA OS with Frigate Addon

**Comment by elderec** [comment]
@dermotduffy - No, still fails when manually clicking play. It fails as @latum  described.

`Device Info: 1.1.2/0.8.4-5043040`

**Comment by Haloooch** [comment]
I'm getting the same issue:

1.1.2/0.8.4-5043040
HA OS with Frigate addon

**Comment by dermotduffy** [comment]
I'm noticing a pattern here, all 1.1.2/0.8.4-5043040 ;-) Let me set up that combo and see if I can reproduce.

**Comment by dermotduffy** [comment]
Figured it out, fairly confident it'll be fixed for you all. I'll do a new build by tomorrow for you to test it out. This would only have been an issue for users of Frigate < 0.9.0 .

**Comment by dermotduffy** [comment]
Hello all,

There's a new pre-release that I believes addresses this issue (v1.0.1): https://github.com/dermotduffy/frigate-hass-card/releases/tag/v1.0.1

Let me know if it works for you?

**Comment by s24dor** [comment]
Hi Dermot, the clips are playing within the card, I haven't checked the rest of the changes, but so far so good. 

Thanks 👍

**Comment by Haloooch** [comment]
Same, confirmed clips are now playing. But not only that, they load very very quickly. I want expecting it to be so smooth, thanks!

**Comment by s24dor** [comment]
I just tested outside my home network and thumbnails load but clips do not play

**Comment by Haloooch** [comment]
@s24dor, I've just tested and can confirm they are playing for me outside my network. No idea why we are seeing different things.

**Comment by latum** [comment]
I can also confirm that the clips play when using the external (Nabu Casa) URL to access HA.  Also that they start very quickly. Well done, thank you very much! Also appreciate the options for the next and previous controls.

**Comment by s24dor** [comment]
Forget my last message, it seems the event that i was trying to view had just deleted after the fifth day and was no longer available.

I have since got the card working remotely on another machine.

Thanks again Dermot

**Comment by dermotduffy** [comment]
Fantastic. Thank you all for testing.
