### ISSUE TITLE
Arbitrary aspect ratio support is not compatible with bleeding edge HA

### ISSUE THREAD

**Issue by utkarshjain00** [dermotduffy/frigate-hass-card#94]
**Release with the issue:**
v1.1.0

**Last working release (if known):**

**Browser and Operating System:**
Edge / Windows 10

```
Logger: frontend.js.latest.202108300
Source: components/system_log/__init__.py:190
First occurred: 4:34:08 PM (11 occurrences)
Last logged: 4:39:01 PM

http://XYZ/hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=394082552110:491:34 Uncaught TypeError: this._elementResized is not a function
```

**Additional information:**

**Comment by dermotduffy** [comment]
What version of Home Assistant are you running?

**Comment by utkarshjain00** [comment]
core-2021.9.7
supervisor-2021.09.6
Home Assistant OS 6.4

**Comment by dermotduffy** [comment]
Thanks. Last one -- what are  you doing when this happens? From that  line of code, looks like maybe you're live viewing a camera -- but perhaps a camera that isn't a Frigate stream camera (e.g. a different camera, or a Frigate MQTT snapshot camera?)

**Comment by utkarshjain00** [comment]
Frigate stream camera - live view only, all was working fine with earlier release. This situations happens randomly but frequently. 

Sometimes this creates a repro - If I try editing the lovelace UI, make some changes, switch tabs, come back to the tab in a few minutes. 

Let me know if anything else I can tell you that helps.

**Comment by dermotduffy** [comment]
I've found a change to the HA frontend between your version of HA, and mine, that removes that function in question. I am going to try to reproduce on my end with a cutting edge version of HA. This bug is in a place that could be more than 1 of the issues you have reported.

I have failed to reproduce any of your issues in Edge with _my_ version of Home Assistant and a tall/portrait camera.

**Comment by utkarshjain00** [comment]
I seem to have the latest version of HA as best as I can tell. If you have
any potential fixes or private release, I can try it for you.

**Comment by dermotduffy** [comment]
Good news: I can reproduce it! (Using a bleeding edge Home Assistant).

**Comment by dermotduffy** [comment]
@utkarshjain00 -- would you mind trying this out (since you offered -- thank you!): 

[frigate-hass-card.zip](https://github.com/dermotduffy/frigate-hass-card/files/7264501/frigate-hass-card.zip)

* You should be able to unzip  and  drop into your `/www/community/frigate-hass-card/` directory (
* (Please delete the file(s) in there before hand so you  don't get stuck with the old build). 
* Make sure you clear your browser cache.

This should fix this issue, but also may fix https://github.com/dermotduffy/frigate-hass-card/issues/90 .

**Comment by utkarshjain00** [comment]
I still see some exceptions in the logs, even after clearing cache, reloading browser etc. Having said that, things seem to be working fine in the limited testing I have done so far. Yes, it seems to have fixed #90 too. 


`
Logger: frontend.js.latest.202108300
Source: components/system_log/__init__.py:190
First occurred: 11:24:54 PM (110 occurrences)
Last logged: 11:25:20 PM

http://XYZ/hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=394082552110:491:34 Uncaught TypeError: this._elementResized is not a function
`

**Comment by dermotduffy** [comment]
Great that it works!

The exception is still complaining  about the same line 491, which used to -- but no longer -- contains a reference to `this._elementResized`. This makes me think somehow you still have something cached. Maybe try from an Incognito/InPrivate window just to be sure? On my side, I only see that error message before my change, but not after.

**Comment by utkarshjain00** [comment]
No problem! Thanks for all the good work and such a quick turnaround on all the bugs. 

Yes, I think you are right. The errors are likely from multiple devices I have where I view the cards. As I refresh/reload the devices, exceptions are going away.
